---
title: "Academic talks"
---

To come: 


2023 [Interactive Causal Learning Conference](http://interactivecausallearning.com/), 1st-2nd December, Florida, USA (talk)


Previous talks:


2023 [CEN2023 Conference](https://cen2023.github.io/home/), 3rd-7th September, Basel, Switzerland (talk)


2023 [European Meeting of Statisticians (EMS)](https://ems2023.org//), 3rd-7th July, Warsaw, Poland (talk)


2023 [Society for Epidemiologic Research](https://epiresearch.org/annual-meeting/2023-meeting/), 13th-16th June, Portland, USA (workshop and two talks)


2023 [American Causal Inference Meeting](https://sci-info.org/annual-meeting/), Austin, Canada (Contributed)


2023 [YES Causal Inference](https://bemcolloquium.com/meetings-calendar/), 13th March, Eindhoven, Netherlands (Invited)

2023 [European Causal Inference Meeting](https://www.eurocim.org/program.html), 18-21 April, Oslo, Norway (Invited course holder and contributed talk)


2023 [TAU Statistics Seminar](https://sites.google.com/view/taustatseminar/home), 3 January, Tel Aviv, Israel (Invited course holder and contributed talk)

2023 [Berlin Epidemiological Methods Colloquium, Germany](https://www.ebpi.uzh.ch/en/aboutus/activities/ebpi-colloquia.html), 11th January, Berlin, Germany (Invited)

2023 [CAUSALab Methods Series at IMM, Karolinska Institutet](https://survey.ki.se/methodsseries), 17th January, Stockholm, Sweden (Invited)

2022 [Center for Causal Inference Fall Seminar](https://www.cceb.med.upenn.edu/cci), 15th September, Online seminar Philadelphia, USA (Invited)


2022 [EFSPI](https://www.efspi.org/EFSPI/Events/Annual_Regulatory_Statistics_Workshops/Next_Meeting/EFSPI/Events/Regulatory_Meetings/7th_EFSPI_Workshop_on_Reglatory_Statistics.aspx?hkey=e3b3c3ef-dd54-4d4a-9115-58833d4cd1e2), 14th September, Basel, Switzerland (Invited)


2022 [International Society for Clinical Biostatistics](https://www.iscb.info/scb-conference-2022/), 21st-25th August, Newcastle, UK (Invited)


2022 [31st International Biometric Conference](https://www.ibc2022.org/home), 10th-15th July, Riga, Latvia (Invited)


2022 [ISPM Bern](https://www.imsv.unibe.ch/research/talks/swiss_statistics_seminars_live/index_eng.html), 10th-15th June, Bern, Switzerland (Invited)

2022 [Society for Epidemiologic Research](https://epiresearch.org/annual-meeting/2022-meeting/), 14th-17th June, Chicago, USA (3 sessions)

2022 [Swiss Statistics Seminar](https://www.imsv.unibe.ch/research/talks/swiss_statistics_seminars_live/index_eng.html), 25 March, Bern 

2022 [University of Waterloo](https://uwaterloo.ca/statistics-and-actuarial-science/events), 24 March, Canada 

2021 CMStatistics, 18th-20th December, London, UK (Invited)

2021 [Online Causal Inference Seminar](https://sites.google.com/view/ocis/), 30th November, USA (Invited discussant) 

2021 Centre for Statistical Methodology Series, 24th November, London School of Hygiene and Tropical Medicine, London (Invited)

2021 Biostatistics Seminar, 13th October, Stockholm, Sweden (Invited)

2021 The 2021 Pacific Causal Inference Conference, September 12th, Beijing, China (Invited)

2021 Oslo Biostatistics Seminar, August 31st, Oslo, Norway (Invited)

2021 JGH Epidemiology Seminar 2021, Montreal, Canada (Invited)

2021 Biometrischen Kolloquium 2021, Germany (Invited)

2021 Society of Epidemiologic Research}, San Diego, USA (Contributed)

2020 CMStatistics, December 19th-21st, London, UK (Invited)

2020  Adolphe Quetelet Seminar Series, December, Ghent, Belgium (Invited)

2020 [Society for Epidemiologic Research](https://epiresearch.org/), Boston, USA (Contributed)

2020 Biostatistics Seminar, October 28th, Basel, Switzerland (Invited)

2020 Statistics Seminar Series, Geneva (Invited)

2020 [Joint Statistical Meeting](https://www.amstat.org/ASA/Meetings/Joint-Statistical-Meetings.aspx), August 3rd, Online Conference (Contributed)

2020 [European Causal Inference Meeting](https://www.eurocim2020.com/), Online Conference (Contributed)

2020 Causal Inference Seminar, Boston University, Boston, USA (Invited)

2019 [Mathematical Colloquium](https://www.uni-ulm.de/en/mawi/faculty/faculty/recurring-events/mathematical-colloquium/) Ulm, Germany (Invited)

2019 [Conference on Lifetime Data Science: Foundations and Frontiers](http://lids2019.pitt.edu/), Pittsburgh, USA (Invited)

2019 [Society for Epidemiologic Research](https://epiresearch.org/annual-meeting/2019-meeting/), Minneapolis, USA (Invited)

2019 [Atlantic Causal Inference Meeting](https://www.mcgill.ca/epi-biostat-occh/news-events/atlantic-causal-inference-conference-2019), Montreal, Canada (Contributed)

2019 [European Causal Inference Meeting](https://eurocim2019.bips.eu/home.html), Bremen, Germany (Contributed)


