---
title: "Teaching"
---

**Teaching at EPFL:**

I teach two full semester courses for mathematics students at EPFL, **Randomization and Causal Inference** (3rd year Bsc in Mathematics) and **Biostatistics** (1st year Msc in Mathematics). Both courses are taught in the Spring semester.  

In September 2022 I also started teaching a course called **Causal Thinking**, which is intended for 3rd year Bsc and 1st year Msc student with different backgrounds, such as computer science, physics, biology and engineering. 

Finally, I teach introductory courses in probability and statistics for students outside of the mathematics department. 

I have also taught doctor courses on advanced causal inference methods at EPFL.

**Previous teaching:**

In 2019 and 2020, I was Miguel Hernan's teaching assistant in HT194 Clinical epidemiology at Harvard Medical School. I also was Jamie Robins's teaching assistant in the advanced epidemiologic methods course EPI207 at Harvard School of Public Health. 

In 2020, I gave 6 hours of lectures in the PhD course MF9570 (Causal Inference) at the University of Oslo. 

In 2020, I held a guest lecture about separable effects in the Harvard Statistics course Stat 293 "Design of Experimental and Non-experimental Studies".

Previously I've taught introductory courses in statistics for MD students at the University of Oslo. I've also held lectures on causal inference in different PhD courses at the University of Oslo and the University of Tromsø.